### ISSUE TITLE
Modification to compile Buster

### ISSUE THREAD

**Issue by lguyome45** [guysoft/ZynthianOS#13]
Hi,
trying docker to compile ZynthianOs, at the beginning problem with git.
I add in Zynthianos/src/modules/zynthianos/start_chroot_script apt -y install git

I alse change bash -x setup_system_rbpi_raspbian_lite_jessie.sh by bash -x setup_system_rbpi_raspbian_lite_buster.sh

Compilation in progress, I will send build.log after

**Comment by lguyome45** [comment]
[build.log](https://github.com/guysoft/ZynthianOS/files/3502707/build.log)

Build of the full process

**Comment by jofemodo** [comment]
I commited the changes in the "Nightly Build" machine, that included the changes you made and some more.

Thanks!

**Comment by lguyome45** [comment]
Ok, great. I finish download the nighty build image and give a try, see what is missing.

**Comment by guysoft** [comment]
Just wanna say its awesome we can reproduce now the build in different locations and fix stuff.

**Comment by guysoft** [comment]
I think this can be closed. right?
